version: "3.9"
services:
  jungmhaDB:
    container_name: jungmha-postgres
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sql@min
    volumes:
      - C:\Items\mysoftwares\JVM\learnKotlinMicronaut\src\main\resources\script.sql:/docker-entrypoint-initdb.d/script.sql
