### GET Request Query Parameters

GET http://localhost:8080/api/process-json?name=bob%20space&value=40

### GET Request Path Variables

GET http://localhost:8080/api/ชามะนาว/30

###

GET http://localhost:8080/api/filter?type=Dessert&price=0

### Nostr Relay Response

GET https://relay.siamstr.com

