### GET Request Query Parameters

GET http://localhost:8080/api/filter?type=Fruit&price=4

### GET Request Path Variables

GET http://localhost:8080/api/ชามะนาว/30

###

GET http://localhost:8080/api
Hellodata: aaa

### Nostr Relay Response

GET https://relay.siamstr.com

